### ISSUE TITLE
Add form validation for user sign up / sign in page

### ISSUE THREAD

**Issue by chiraag-kakar** [chiraag-kakar/sharenlearn#10]
The form validation should be for the following fields :
* First Name  
* Last Name
* Email
* Department
* Contact
* Role
* Password
Note: Make all the fields *required*

**Comment by magjoy6** [comment]
I also want to fix this issue.

**Comment by uttu2** [comment]
I would like to contribute to this.

**Comment by djm-1** [comment]
I would like to work on this issue. Assign it to me for JWoC

**Comment by chiraag-kakar** [comment]
@uttu2, before I assign this issue to you can you brief how you're gonna implement this feature ?

**Comment by uttu2** [comment]
@chiraag-kakar I think that modifying signup function in views.py by adding various check like f variable where firstname is being recieved should be a string and similarly for other fields should do it. Required field can be made just by adding required in the html tag should do it. 
I am new to this so i am still reading about it .

**Comment by chiraag-kakar** [comment]
@uttu2 I am assigning this issue to you

**Comment by 7saikat7** [comment]
we can use form validation like if 
from  p= name.cleaned_data
and if p.is_valid :
       pro=p.save(commit=false)
       pro.save()

something like that !

**Comment by 435akashjha** [comment]
Are you contributing to this issue or should I work Saikat on this
