### ISSUE TITLE
[Need] Issue and PR templates

### ISSUE THREAD

**Issue by Aryamanz29** [chiraag-kakar/sharenlearn#103]
Currently there no issue and PR templates in this repo

**Comment by Aryamanz29** [comment]
I would like to work on this issue , Please add relevant labels and kindly assign it to me

**Comment by Aayush-hub** [comment]
@harshita2216 This needs to be done!

**Comment by Aryamanz29** [comment]
@harshita2216 @amanjha8100  Getting no response from the past 28 days in this issue thread. I decided to raise PR without assigning it to me. This is really bad that the project maintainer doesn't even check open issues.
