### ISSUE TITLE
DARK MODE UI

### ISSUE THREAD

**Issue by mohammedjameel24** [chiraag-kakar/sharenlearn#105]
##Dark Mode UI

**Comment by 435akashjha** [comment]
I want to fix this issue and implement dark mode in website

**Comment by chiraag-kakar** [comment]
Hey @435akashjha @mohammedjameel24  , please share more details on how you're gonna be implementing the dark theme with respect to current color pallete of the project :)

**Comment by mohammedjameel24** [comment]
Pitch black for background and bold white on fore ground inversion of some solid colors

**Comment by 435akashjha** [comment]
This can be done with background color as black and font as white with a toggle button

**Comment by simranbhalla3** [comment]
I am a Gssoc participant , please assign me this issue.
