### ISSUE TITLE
Prevention of logged in user from visiting login/signup page and updated the navbar

### ISSUE THREAD

**Issue by pranjalg13** [chiraag-kakar/sharenlearn#106]
The main issue was the logged-in user, can visit the login page by just going to localhost/index page, even they are logged in they can see the login and admin login navbar.
Secondly, there should be an option to visit the index page from the profile page, so I add the URL for that.

**Comment by pranjalg13** [comment]
@chiraag-kakar Please review the PR and let me know the feedback.
Thanks in advance.

**Comment by Upasana1216** [comment]
Please assign this to me under GSSOC

**Comment by pranjalg13** [comment]
Hey, @Upasana1216 I have already created PR for that. Try to solve the open issues where PR are not pushed or create your own issues if you find any.

**Comment by amanjha8100** [comment]
Ok I will review your PR today. Keep contributing more.
