### ISSUE TITLE
Making contact form more attractive.

### ISSUE THREAD

**Issue by dhananjayd1729** [chiraag-kakar/sharenlearn#108]
Hey @chiraag-kakar @harshita2216 @amanjha8100 ,since the contact page looks too simple and old school, can I make it more attractive so that UI will look much better than now? I'm GSSOC'21 participant can I work on this?

![Screenshot from 2021-03-17 00-02-17](https://user-images.githubusercontent.com/61632269/111361955-46809800-86b4-11eb-9d99-e2228fd89221.png)

**Comment by amanjha8100** [comment]
One pr is under consideration for that issue, if it is not solved ,we will assign it to you.

**Comment by dhananjayd1729** [comment]
Ok. Thanks.

**Comment by dhananjayd1729** [comment]
> One pr is under consideration for that issue, if it is not solved ,we will assign it to you.

@amanjha8100  Is pr got merged that you were talking about?

**Comment by harshita2216** [comment]
@dhananjayd1729 The PRs will be merged by the project admin. We will create the issue again if the PR under review is not accepted.
