### ISSUE TITLE
Creating profile picture section in signup form

### ISSUE THREAD

**Issue by 435akashjha** [chiraag-kakar/sharenlearn#109]
Creating a profile picture in signup will help users to identify others .

**Comment by 435akashjha** [comment]
I  want to work on this issue and contribute to this project

**Comment by Mus2413** [comment]
Hello,  I would like to contribute on this project. Could you please assign me this issue.

**Comment by harshita2216** [comment]
Hey both, we currently do not need this. Will reopen this once we require this. ;)
