### ISSUE TITLE
Add form validation for the admin login page 

### ISSUE THREAD

**Issue by chiraag-kakar** [chiraag-kakar/sharenlearn#11]
* Validate the form elements and make the fields required.

**Comment by magjoy6** [comment]
bhaiya @chiraag-kakar , I would like to fix this issue.

**Comment by magjoy6** [comment]
and I am from JWoC  itself

**Comment by 435akashjha** [comment]
I will fix this issue assign to me

**Comment by pankajkumarbij** [comment]
I would like to work on this issue, please assign it to me.
