### ISSUE TITLE
Adding username input in login page of users

### ISSUE THREAD

**Issue by 435akashjha** [chiraag-kakar/sharenlearn#110]
It will help users to add their own username

**Comment by 435akashjha** [comment]
I  want to work on this issue

**Comment by harshita2216** [comment]
@435akashjha Not sure if we need this at the moment. Will consider you if we feel it is required.

**Comment by 435akashjha** [comment]
@harshita2216  Should this issue needs to be close for now

**Comment by harshita2216** [comment]
@435akashjha Yes, you may.
