### ISSUE TITLE
Creating Password validation in Signup form

### ISSUE THREAD

**Issue by 435akashjha** [chiraag-kakar/sharenlearn#113]
A password validation can be added such as min and max characters allowed for password and condition of uppercase and lowercase letters and one special characters for generating strong passwords.

**Comment by RahulPalve** [comment]
hey @harshita2216  can u label my pr with gssoc21

**Comment by harshita2216** [comment]
@RahulPalve Your PR will not be considered as it is already assigned to someone.

**Comment by RahulPalve** [comment]
So, if someone raise the issue it will be assigned to that person by default? 🙄.

**Comment by harshita2216** [comment]
@RahulPalve No, but you need to comment on the issue first and get assigned before making a PR. Your comment decides whether or not you will be picked for working on the issue. Ideally, we want you to comment on how you are going to solve the issue. 
These are some rules given by GSSoC and they expect both mentors and participants to follow.

**Comment by ANAMIKA1410** [comment]
import re 
password = "R@m@_f0rtu9e$"
flag = 0
while True:   
    if (len(password)<8): 
        flag = -1
        break
    elif not re.search("[a-z]", password): 
        flag = -1
        break
    elif not re.search("[A-Z]", password): 
        flag = -1
        break
    elif not re.search("[0-9]", password): 
        flag = -1
        break
    elif not re.search("[_@$]", password): 
        flag = -1
        break
    elif re.search("\s", password): 
        flag = -1
        break
    else: 
        flag = 0
        print("Valid Password") 
        break
  
if flag ==-1: 
    print("Not a Valid Password")

**Comment by harshita2216** [comment]
@435akashjha I am unassigning you from this issue as we've not heard from you in 7 days.

**Comment by 435akashjha** [comment]
Please give me a day I will solve it.

**Comment by harshita2216** [comment]
> Please give me a day I will solve it.

Okay, make a PR by tomorrow.

**Comment by Abhishekkr93** [comment]
I would like to contribute as a Gssoc21 participant. could you please assign me this? I will create this.

**Comment by RahulPalve** [comment]
PR ready to be merged :
https://github.com/chiraag-kakar/sharenlearn/pull/117
