### ISSUE TITLE
Login form not displaying errors.

### ISSUE THREAD

**Issue by nikhilkotiya** [chiraag-kakar/sharenlearn#114]
![Screenshot (93)](https://user-images.githubusercontent.com/51186856/111421992-f0434180-8713-11eb-93ef-2c0c9ee3b183.png)

When debug is false then this error is not show

**Comment by Shulabh-968026** [comment]
I world like resolve this issue.Can I work on it.

**Comment by nikhilkotiya** [comment]
@Shulabh-968026 Bro i want to work in this issue , sorry

**Comment by harshita2216** [comment]
@nikhilkotiya @Shulabh-968026 Hey we have fixed the errors. Please update your fork. If there are still errors, please let us know in the project channel. Closing the issue for now.
