### ISSUE TITLE
Enhancing the /upload_notes page

### ISSUE THREAD

**Issue by djm-1** [chiraag-kakar/sharenlearn#12]
I want to work on the front end of this page https://wecreate.pythonanywhere.com/upload_notes. Including a custom file upload button, beautifying the form and complete layout. Can you assign this to me for JWOC ?

**Comment by chiraag-kakar** [comment]
@djm-1 I am assigning this issue to you. 
Please add the relevant labels to this issue

**Comment by djm-1** [comment]
Thank you

**Comment by djm-1** [comment]
I have created the PR. https://github.com/chiraag-kakar/sharenlearn/pull/20
