### ISSUE TITLE
Google, Facebook sign in

### ISSUE THREAD

**Issue by balarka135** [chiraag-kakar/sharenlearn#126]
I think on the login page, we have to implement google and Facebook sign-in and sign-up.
Because sometimes it very time-consuming to fill the form.

I like to work on the issue. Please assign me

**Comment by Aj7t** [comment]
🚀hello, I am a member if Gssoc'21. plz assign me this issue, I  will do it   as earliest as possible

**Comment by chiraag-kakar** [comment]
Hey @balarka135, @Aj7t  really appreciate your enhancement , however we don't require social auth in this project. The reason being , you can only fetch details like profile picture , email from the social handles of users but this project requires users to enter more specific details. Do checkout the registration page again :)
