### ISSUE TITLE
viewall_usernotes.html is not responsive.

### ISSUE THREAD

**Issue by kanishka8276** [chiraag-kakar/sharenlearn#127]
The table in Accepted_notes.html is not responsive.
Due to which we have to scroll horizontally to view the table's content.

**Comment by chiraag-kakar** [comment]
Hey @kanishka8276 , ping with the issue number in the project channel and the mentors will assign you this issue , also try to attach some screenshots while you are creating issues or PRs , it becomes easier to follow your enhancements :)

**Comment by Nishayadav-bit** [comment]
Hello, I would like to work on this issue .Please assign to me ,I'm a participant in GSSOC'21
