### ISSUE TITLE
Preloader

### ISSUE THREAD

**Issue by nikhilkotiya** [chiraag-kakar/sharenlearn#129]
I want to add a preloader for this project.
I am a gssoc'21 participant and want to contribute on this project.

**Comment by chiraag-kakar** [comment]
Hey @nikhilkotiya , ping with the issue number in the Discord channel and mentors will assign you the issue.

**Comment by nikhilkotiya** [comment]
@chiraag-kakar Now can I start work in this issue?

**Comment by amanjha8100** [comment]
assigning this to you!

**Comment by SnehaVeerakumar** [comment]
If limit limit exceeds for current assignee, kindly assign me.
If assigned, I will complete this within 1 day.

**Comment by harshita2216** [comment]
@nikhilkotiya I've not heard from you after I requested changes on Discord. Hence, I'm assigning this to @SnehaVeerakumar.

**Comment by SnehaVeerakumar** [comment]
As you told you requested for changes, may I know that for proceeding further? @harshita2216

**Comment by harshita2216** [comment]
@SnehaVeerakumar The changes I requested was for his PR. You can proceed with your work. In case you need to discuss something, you can drop me a message on Discord.

**Comment by SnehaVeerakumar** [comment]
I will make a PR by tomorrow. Sorry for the delay due to my exams.
