### ISSUE TITLE
[GSSoC'21] Page Not Found

### ISSUE THREAD

**Issue by arpit456jain** [chiraag-kakar/sharenlearn#130]
Hello @chiraag-kakar sir I am gsoc'21 participant , I don't know this is a bug  or I made any mistake in the process of getting-started. Home page is ok but when i clicked on  about and contact page i got **page not found error** .I am attaching a video Please check it , If this is really a issue i would love to solve it.
Please assign it to me . I will solve it as soon as possible.

https://user-images.githubusercontent.com/55352601/111903803-f3b72f80-8a69-11eb-963a-011bd2d5afd2.mp4

**Comment by chiraag-kakar** [comment]
Hey @arpit456jain , if you check out the deployed version https://sharelearn.herokuapp.com which is updated with the latest codebase is working fine. Kindly clone the repository and follow the set up docs again :)

**Comment by arpit456jain** [comment]
ok sir

**Comment by arpit456jain** [comment]
@chiraag-kakar Sir When i visit url given by you above I got this page <img width="960" alt="sh" src="https://user-images.githubusercontent.com/55352601/111907408-2cabd000-8a7b-11eb-8c95-d9632b22fd7d.png">

**Comment by arpit456jain** [comment]
@chiraag-kakar  sir I had clone it again just 2 min before but still i am facing the same issue page not found Please take a look into it.

**Comment by chiraag-kakar** [comment]
@arpit456jain , check out the following links , there was a typo in previous link provided :)
https://sharenlearn.herokuapp.com/
https://sharenlearn.herokuapp.com/about

**Comment by arpit456jain** [comment]
ok sir
