### ISSUE TITLE
[GSSOC' 21] [FEATURE] [BACKEND] Adding social login

### ISSUE THREAD

**Issue by Aditya201551** [chiraag-kakar/sharenlearn#131]
@chiraag-kakar I would like to add social login to this project i.e Google and Facebook login, please assign me this task

Thank You(GSSOC' 21 participants)

**Comment by chiraag-kakar** [comment]
Hey @Aditya201551 really appreciate your enhancement , however we  don't require social auth in this project. The reason being , you can only fetch details like profile picture , email from the social handles of users but this project requires users to enter more specific details. Do checkout the registration page again :)
