### ISSUE TITLE
Gssoc'21 Adding Form Validation And Error/Success message in Contact page

### ISSUE THREAD

**Issue by arpit456jain** [chiraag-kakar/sharenlearn#132]
Hello @chiraag-kakar sir i am a gssoc'21 participant and i want to add some form validation in contact page because I think there are no validations in it as i am able to fill all fields by 'a' and it got submitted successfuly and some flash message feature using message framework in Django Kindly Assign me this issue I will do this as soon as possible.

**Comment by arpit456jain** [comment]
Can I start working on it @codeit13 sir

**Comment by harshita2216** [comment]
Comment on #111 and close this. 
Don't create same issues again. @arpit456jain 

Comment your approach as well to have better chances of getting assigned.

**Comment by arpit456jain** [comment]
ok mam
