### ISSUE TITLE
vir folder is not required 

### ISSUE THREAD

**Issue by flyingsonu122** [chiraag-kakar/sharenlearn#139]
this folder has been created by the **maintainers** while creating virtual environment, this should not be uploaded 

so, **delete it**  and add instructions in README.md for deleting the virtual environment folder before pushing

**Comment by flyingsonu122** [comment]
@chiraag-kakar @harshita2216 @amanjha8100 please assign this to me

**Comment by flyingsonu122** [comment]
this has made it like this

![image](https://user-images.githubusercontent.com/51280276/112326460-8bbb5000-8cda-11eb-95d9-906195c216b0.png)

**Comment by flyingsonu122** [comment]
see the **impact**

![image](https://user-images.githubusercontent.com/51280276/112327558-88749400-8cdb-11eb-9161-6d28f492cae4.png)

**Comment by flyingsonu122** [comment]
you do not need it 

check here [How?](https://stackoverflow.com/questions/6590688/is-it-bad-to-have-my-virtualenv-directory-inside-my-git-repository)

**Comment by harshita2216** [comment]
Please check the project channel. Thanks.

**Comment by chiraag-kakar** [comment]
Hey @flyingsonu122 , really appreciate your suggestion to improve the project directory structure , however we cannot consider this as an issue for the following reasons : 
* Each Contributor is free to name virtual environment according to his/her choice.
* Secondly it is the responsibilty of the contributor to include that virtual environment directory in the ```.gitignore``` file.

Practically it is not possible for the maintainers to change the vir for every contributor. As of now the existing vir directory  is not creating any issue as such as the LFS is enabled for this repository.

I hope you are clear with why we don't need this as an issue :)
