### ISSUE TITLE
Select branch and filetype dropdowns in upload_notes.html

### ISSUE THREAD

**Issue by sakshi-s** [chiraag-kakar/sharenlearn#141]
The menu currently looks like the image below in which options are scattered.
![before](https://user-images.githubusercontent.com/39264146/112529150-f77ce600-8dca-11eb-9447-d205570f71a1.PNG)

I will change it to an organized dropdown like :
![after](https://user-images.githubusercontent.com/39264146/112529312-22ffd080-8dcb-11eb-9aad-19b7aa67f2ef.PNG)

**Comment by harshita2216** [comment]
Assigning it to you but make sure your changes complement the overall animation of this page. Apply some styles to the drop-down. @sakshi-s

**Comment by simranbhalla3** [comment]
I am a Gssoc participant , please assign me this issue.
