### ISSUE TITLE
Bug In changepassword.html

### ISSUE THREAD

**Issue by kanishka8276** [chiraag-kakar/sharenlearn#147]
The changepassword.html allows user to keep empty password. I would like to add validation for it.
Please assign this to me.
GSSoC'21

**Comment by simranbhalla3** [comment]
I am a Gssoc participant , please assign me this issue.

**Comment by Naman-12911** [comment]
Hello I am a participant of GSSOC I want to solve this issue please assign me.

**Comment by harshita2216** [comment]
Someone has already worked on this issue. I request you not to create same issues again and again. Please comment on them instead.
