### ISSUE TITLE
Notes Model has no field called "signup"

### ISSUE THREAD

**Issue by Abhra303** [chiraag-kakar/sharenlearn#15]
The notes model has no field called signup. But the str method of notes model returns self.signup.user.username which does not exist. For this reason django is throwing error when saving notes objects.
![image](https://user-images.githubusercontent.com/75240995/105378175-8cc7f680-5c31-11eb-9c89-33c3c15d49b8.png)

**Comment by Abhra303** [comment]
Hello I want to contribute in this issue under jwoc

**Comment by chiraag-kakar** [comment]
@Abhra303  , I am assigning this issue to you :)
