### ISSUE TITLE
UI Enhancements for Home Page

### ISSUE THREAD

**Issue by hariramjp777** [chiraag-kakar/sharenlearn#152]
Hi, I'd like to improve the UI of the Home page.

Here's a UI created using Figma. I'd like to code it using HTML (Django) and CSS.

![Home](https://user-images.githubusercontent.com/58631762/116806643-1e59d500-ab4c-11eb-81d8-0016577e8b6d.png)

Please Assign this to me @harshita2216

**Comment by Malvika18** [comment]
hey i want to contribute to this issue , please assign this to me
