### ISSUE TITLE
Change in color of link in footer

### ISSUE THREAD

**Issue by AasthaCodex** [chiraag-kakar/sharenlearn#154]
The footer sitemap color is not that visible, It should be changed to a lighter shade. 
<img width="357" alt="Capture4" src="https://user-images.githubusercontent.com/72413064/113511657-871a5580-957e-11eb-9b66-d4340cd5b8a2.PNG">

on hovering it looks more darker in shade

**Comment by simranbhalla3** [comment]
I am a Gssoc participant , please assign me this issue.

**Comment by harshita2216** [comment]
Hey both, please check our discord server in a few days. We've been planning something for the project and for that we do not require this issue. Will announce as soon as we get the confirmation from the PA.
