### ISSUE TITLE
Alignment of navbar

### ISSUE THREAD

**Issue by Fpj-11** [chiraag-kakar/sharenlearn#155]
Navbar can be shifted towards right side. Also hover effects of navbar can be changed.
I am interested in front-end development. Can I work on this issue?

**Comment by jugeshraghav** [comment]
I am interested in this. Please assign me this issue.

**Comment by harshita2216** [comment]
Hey both, please check our discord server in a few days. We've been planning something for the project and for that we do not require this issue. Will announce as soon as we get the confirmation from the PA.
