### ISSUE TITLE
discussion panel such as a Chat room

### ISSUE THREAD

**Issue by giridhar7889** [chiraag-kakar/sharenlearn#156]
A discussion panel can be implemented where students can post their requests to the faculty to upload the study materials and can discuss various things related to the availability of open-source materials he/she found out and share that material as it will be available to every single one of them.

**Comment by giridhar7889** [comment]
@chiraag-kakar can you please assign this to me?

**Comment by harshita2216** [comment]
@giridhar7889 This is currently not required. Will reopen if we need this. :)
