### ISSUE TITLE
bug the responsive login form 

### ISSUE THREAD

**Issue by MennaMagdy2019** [chiraag-kakar/sharenlearn#157]
can I solve this bug I will make it responsive and solve it on this screen and I will make a scroll bar at the same color of the background?
![Capture1](https://user-images.githubusercontent.com/50016070/114109898-8fec8d80-98d6-11eb-93cf-bd70c55f7456.PNG)

 I am a GSSOC participant, please assign me this issue. @harshita2216?

**Comment by harshita2216** [comment]
@MennaMagdy2019 this page has 2 signup forms, we only need one. Please fix that as well.

**Comment by harshita2216** [comment]
@MennaMagdy2019 I am sorry but we already have this issue assigned to someone.
