### ISSUE TITLE
Add Google Login Feature

### ISSUE THREAD

**Issue by ashutoshkrris** [chiraag-kakar/sharenlearn#159]
I'd like to add google login feature so that user need not fill a form to login or sign up.

**Comment by harshita2216** [comment]
@ashutoshkrris We cannot have this feature as while signing up we need additional details which Google login wouldn't give us.

**Comment by ashutoshkrris** [comment]
> @ashutoshkrris We cannot have this feature as while signing up we need additional details which Google login wouldn't give us.

But after login, we could have redirected the user to a page where he/she could fill up those additional details (only once).
Anyways, no issue.
