### ISSUE TITLE
Simple Notify to show messages(error, warning or success)

### ISSUE THREAD

**Issue by ashutoshkrris** [chiraag-kakar/sharenlearn#161]
Commonly, we use Bootstrap alerts to show messages. But it looks a bit old fashioned. We can use a light weight notification tool for this. Below is the attached demo for the same.
![Screenshot (319)](https://user-images.githubusercontent.com/47353498/114172219-0038f480-9953-11eb-90fc-31eaa07734e1.png)
The above notification shows up in the right top corner of the page which looks far better than Bootstrap alerts

**Comment by harshita2216** [comment]
@ashutoshkrris Closing this as this is already listed and a PR for the same is under review. :)
