### ISSUE TITLE
Forgot password with OTP Verification

### ISSUE THREAD

**Issue by ashutoshkrris** [chiraag-kakar/sharenlearn#173]
There are a lot of extra fields like First Name, Last Name in the forgot password page. Also, instead of directly changing user's password, we can first verify if the user is a authentic user using OTP verification. Also, we can implement Ajax validation.
I have attached a screenshot of the forgot password page.
![Screenshot (325)](https://user-images.githubusercontent.com/47353498/114262009-274b0100-99fb-11eb-92d1-57cd4cb382d3.png)

**Comment by AVS18** [comment]
Please work on this issue and make sure you try to use username/email enter and change the password based on otp.
All the best

**Comment by ashutoshkrris** [comment]
@AVS18 
Of course, I will be using email field to check if the user exists. If it does, an OTP will be sent on the same. No phone number will be involved in the entire process.

**Comment by AVS18** [comment]
cool.

**Comment by ashutoshkrris** [comment]
> cool.

Kindly assign me this issue.
I thought, I was already assigned and hence made a PR
