### ISSUE TITLE
There is an extra form in user login page and page is not completely responsive

### ISSUE THREAD

**Issue by Dkarya846** [chiraag-kakar/sharenlearn#174]
https://sharenlearn.herokuapp.com/login page has an extra form and the page is not completely responsive too.

**Comment by jugeshraghav** [comment]
Can I take up this issue?

**Comment by harshita2216** [comment]
This has already been fixed. The PR is yet to be merged. @Dkarya846 @jugeshraghav

**Comment by Dkarya846** [comment]
OKay, thank you
