### ISSUE TITLE
[BUG] [GSSOC' 21] Bug in login page

### ISSUE THREAD

**Issue by Aditya201551** [chiraag-kakar/sharenlearn#179]
- There are two login forms in login page one with proper orientation and another with improper orientation, reference video is given below:

https://user-images.githubusercontent.com/32588231/114309408-a24c0e80-9b04-11eb-8fff-9d7eceafc9bf.mp4

@chiraag-kakar @AVS18 @amanjha8100 i would like to fix up this page please assign me this issue

**Comment by harshita2216** [comment]
@Aditya201551 We already have a PR approved for this issue. :)

**Comment by Aditya201551** [comment]
@harshita2216 okay

**Comment by subhangi2731** [comment]
please assign me this

**Comment by Aditya201551** [comment]
i have fixed the issue
