### ISSUE TITLE
[gssoc'21]Preloader feature

### ISSUE THREAD

**Issue by archanagandhi** [chiraag-kakar/sharenlearn#183]
hey @chiraag-kakar 
I would like to add a new preloader feature to the website. 
please assign this to me
Thanks

**Comment by harshita2216** [comment]
@archanagandhi We already have this issue. #129

**Comment by archanagandhi** [comment]
hey @harshita2216  It's been 27days since the issue has created. please assign this to me.  will submit within 2 days
