### ISSUE TITLE
[GSSOC' 21] [BUG] Favicon not available in everypage

### ISSUE THREAD

**Issue by Aditya201551** [chiraag-kakar/sharenlearn#188]
- Favicon is not applied on every page
- It's only present on the home page, the rest of the page does not contain any favicon

![Screenshot 2021-04-20 135739](https://user-images.githubusercontent.com/32588231/115363806-67229d00-a1e0-11eb-86b5-eabfa0307ca4.png)

@chiraag-kakar @harshita2216 i would like to fix this issue please assign me this issue

**Comment by amanjha8100** [comment]
Favicon is loading for every page on the original website, I would suggest in your runserver check the status of favicon, check the source img file and then update me.

**Comment by Aditya201551** [comment]
@amanjha8100 yes its working fine on the original website, sorry gonna close this issue then
