### ISSUE TITLE
Revamp About Page 

### ISSUE THREAD

**Issue by harshita2216** [chiraag-kakar/sharenlearn#189]
Currently the about page loading is slow.  This could be because of unnecessary code and large image size. Please comment how are you going to work on this?

**Comment by tanishq-arya** [comment]
@harshita2216 Please assign me this issue.
Proposed changes:
1. Remove excess scripts
2. Covert all scripts to a single .js file 
3. Add a suitable illustration to the page and remove the background image. 
4. Style the font
5. Structure the sections using css grid layout.
