### ISSUE TITLE
Admin login are duplicated

### ISSUE THREAD

**Issue by kanisshka** [chiraag-kakar/sharenlearn#191]
# Prerequisites:

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I checked to make sure that this issue has not already been filed.

- [x] I'm reporting the issue to the correct repository (for multi-repository projects) **(optional)**

# Expected Behavior:

There should be only one admin login box.

# Current Behavior:

It is showing 2 containers for login.

# Solution: 

I try to manage that page.

# Screenshots (optional):
![image](https://user-images.githubusercontent.com/76627599/116426371-aeec9880-a860-11eb-83e3-55d9dbb73fa0.png)
![image](https://user-images.githubusercontent.com/76627599/116426427-b9a72d80-a860-11eb-95c9-8fe54472c2b1.png)

Please assign me this issue under GSSoC'21.

**Comment by harshita2216** [comment]
Hey we are updating the entire UI. Someone is already working on this. :)
