### ISSUE TITLE
Username

### ISSUE THREAD

**Issue by RuchiGitHu** [chiraag-kakar/sharenlearn#194]
### Feature request-
In the Login page, there should be username option also. As in admin login the username is required to fill. But for existing one, there is no username in login page. How the user can login only with password?
I want to add username option there.
![image](https://user-images.githubusercontent.com/71754179/116812800-3c383180-ab6e-11eb-8492-c8adb5e66370.png)

### Describe the solution you'd like
I will add username option in login page.

### Describe alternatives you've considered
NA

### Describe how this feature will be useful to our readers.
If I have account from two userame but passwod is same for both the username, then after entering only password the user can be login from one username, but what if user want to login from second username by using same password.

### Additional context
![image](https://user-images.githubusercontent.com/71754179/116812917-e3b56400-ab6e-11eb-82ce-1df39dcab535.png)

Please let me know if image is visible to you..
I an participant of gssoc21.
<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by harshita2216** [comment]
@RuchiGitHu We are updating the entire UI of Share N Learn and someone is already working on that.
