### ISSUE TITLE
Add Footer to the about page.

### ISSUE THREAD

**Issue by Shivangi-ch** [chiraag-kakar/sharenlearn#196]
### Feature request-
I would like to add the footer to about page.

### Is your feature request related to a problem? Please describe. (optional)
No. 

### Describe how this feature will be useful to our readers.
This will make UI attractive and will give the page an ending.

### Additional context
The footer would be simiar to that of current home page.

<hr/>
I am  a GSSOC participant.
Please assign this to me.

**Comment by harshita2216** [comment]
Hey @Shivangi-ch, we already have a footer which will be extended to the about page.
