### ISSUE TITLE
Add user-friendly hovering effect to the login button on home page. 

### ISSUE THREAD

**Issue by Shivangi-ch** [chiraag-kakar/sharenlearn#197]
### Feature request-
I would like to add user-friendly hovering effect to the login button on home page. 

### Is your feature request related to a problem? Please describe. (optional)
NO.

### Describe how this feature will be useful to our readers.
It will make the page more user friendly.

<hr/>

* I am  a  GSSoC'21 participant.
Please assign this to me.

**Comment by harshita2216** [comment]
How are you going to do it? @Shivangi-ch
