### ISSUE TITLE
Dynamic Social media icons

### ISSUE THREAD

**Issue by arpit456jain** [chiraag-kakar/sharenlearn#198]
I would like to make social media icons in footer to be dynamic like when user hover on them they will rotate .
like this

https://user-images.githubusercontent.com/55352601/116842846-9cc18000-abfb-11eb-9275-1286c57dc29a.mp4

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/117012881-fcf41700-ad0c-11eb-9be5-3aa2b8dcba90.mp4

@harshita2216 I have made the social icons dynamic may i create a PR for this

**Comment by arpit456jain** [comment]
May i create a PR for this.
It will not affect any thing in the website

**Comment by harshita2216** [comment]
No, please don't until you are assigned the issue. I'll let you know how this is to be done. @arpit456jain

**Comment by arpit456jain** [comment]
Ok
