### ISSUE TITLE
Beautify the Navbar

### ISSUE THREAD

**Issue by chiraag-kakar** [chiraag-kakar/sharenlearn#2]
## The following changes need to be implemented in the navbar section :
* Make the navbar sticky and *add* a nice *background color* to the navbar section.
* Implement the *button hover effects* in the menus.
* The navbar should be *responsive*.
* It should have *drawer navigation* in responsive view.

**Comment by pankajkumarbij** [comment]
I would like to work as a participant in JWOC.

**Comment by chiraag-kakar** [comment]
@pankajkumarbij follow the README and try to set up and run the project locally.

**Comment by chiraag-kakar** [comment]
Issues can't be assigned before 21st Jan

**Comment by Pabitra145** [comment]
https://jwoc2k20.tech/

**Comment by Pabitra145** [comment]
As a part of jwoc , i  would like to work on it

**Comment by nilisha-jais** [comment]
I would like to work on it(Participant of JWOC)

**Comment by Vinamrata1086** [comment]
Can I work on this issue?(JWOC)

**Comment by djm-1** [comment]
I would like to add a great looking navbar along with a logo. Please assign this to me for JWOC

**Comment by chiraag-kakar** [comment]
@Pabitra145 , @Vinamrata1086, @djm-1 only one can be assigned an issue at a time. If the issue is not solved by the assignee in 1 day then it will be assigned to the next participant.
