### ISSUE TITLE
Landing Page UI Improvements

### ISSUE THREAD

**Issue by SpecTEviL** [chiraag-kakar/sharenlearn#219]
- [x ] I checked to make sure that this issue has not already been filed.

- [ ] I'm reporting the issue to the correct repository (for multi-repository projects) **(optional)**

# Expected Behavior:

Adding Hover effects and many more changes to the landing page

# Current Behavior:

There are no/very few hover effects which make the UI a bit dull

# Solution: 

I would like to improve upon the UI.

**Note:**
* Do mention if you are working under GSSoC'21. (Yes under GSSoC21)

**Comment by harshita2216** [comment]
I think the UI is okay at the moment. We are currently looking for people to work on some backend issues.
