### ISSUE TITLE
Adding Top- button

### ISSUE THREAD

**Issue by SamikshaSankar** [chiraag-kakar/sharenlearn#251]
### Feature request-
Adding scroll top-button

### Is your feature request related to a problem? Please describe. (optional)
No

### Describe the solution you'd like
I want to add Top-Button

### Describe alternatives you've considered
N/A

### Describe how this feature will be useful to our readers.
When user can scroll down by using top-button they can go to home section.
Please assign this task to me
<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by SamikshaSankar** [comment]
In which html ,css ,js file I have added code...it's confusing me bcz there are more than one html,css, js file..please help me

**Comment by harshita2216** [comment]
Please drop a message in the project channel on Discord.
