### ISSUE TITLE
Add a Sign Up button to the Header

### ISSUE THREAD

**Issue by N-Shar-ma** [chiraag-kakar/sharenlearn#255]
### Feature request-
A Sign Up button should be added beside the Log In button in the header to make onboarding easier for new users. 

### Is your feature request related to a problem? Please describe. (optional)
When a new user views the website, there is no direct link to the sign up page which can be confusing and is bad UX

### Describe the solution you'd like
A button like Login in the header leading to the sign up page will make it easier for new users to create an account! Thhis button will only be there when the user is not logged in. My proposed solution will look like this:
- ![image](https://user-images.githubusercontent.com/68962290/118508425-0ce40180-b6e4-11eb-860a-3422621c4c4f.png)

### Describe how this feature will be useful to our readers.
First time users of this website will find it much easier to create an account by just 1 click, instead of looking around for ways to sign up and not log in

### Additional context
I would like to fix this issue under GSSoC'21, please assign it to me

**Comment by harshita2216** [comment]
Hey, I think it will be better if you do not put so much space. Let the two buttons be aligned closely. 

Also, how will this look in the mobile view?

**Comment by N-Shar-ma** [comment]
## Mobile View:
![image](https://user-images.githubusercontent.com/68962290/118513196-53d3f600-b6e8-11eb-8215-bb5570a3a2ef.png)

## Desktop View:
![image](https://user-images.githubusercontent.com/68962290/118513306-72d28800-b6e8-11eb-94af-50de0852d571.png)

@harshita2216

**Comment by harshita2216** [comment]
Great!

**Comment by N-Shar-ma** [comment]
Thanks @harshita2216! Should I make pull request for this issue?

**Comment by harshita2216** [comment]
Yes, sure. Go ahead @N-Shar-ma
