### ISSUE TITLE
New Banner for README.

### ISSUE THREAD

**Issue by tanishq-arya** [chiraag-kakar/sharenlearn#275]
### Feature request-
I would like to design a new banner for the readme.

**Comment by tanishq-arya** [comment]
Please assign me this issue. @harshita2216

**Comment by chiraag-kakar** [comment]
@tanishq-arya , make sure that the Share N Learn logo is included in the Banner :)

**Comment by tanishq-arya** [comment]
@chiraag-kakar Please take a look at this. I kept it simple. Do let me know your thoughts on this. 
![image](https://user-images.githubusercontent.com/77333275/119251288-8dfb3700-bbc3-11eb-923e-032a5c763c66.png)

**Comment by Kumud-869231165** [comment]
I can design a new banner. Can you assign me this @chiraag-kakar

**Comment by harshita2319** [comment]
Hey, I'm a GSSOC participant and I'd like to work on this issue @harshita2216

**Comment by harshita2216** [comment]
@Kumud-869231165 and @harshita2216 share your designs on discord channel.

**Comment by tanishq-arya** [comment]
@chiraag-kakar How is this ?
![](https://cdn.discordapp.com/attachments/822032957010346045/847139448759910450/Banner_design.jpg)

**Comment by harshita2319** [comment]
> @Kumud-869231165 and @harshita2216 share your designs on discord channel. 

Okay

**Comment by harshita2216** [comment]
> Is it done already or do we have to share more designs on discord? @harshita2216

Yes sure you can do.
