### ISSUE TITLE
Improve Contact Section

### ISSUE THREAD

**Issue by chiraag-kakar** [chiraag-kakar/sharenlearn#4]
The improvements that need to be made in the contact section include :
* Implementing a Contact Form for collecting users' queries.
* Add SMTP configuration in the settings.py module
* Creating a new view for the contact page (template) that utilizes *SMTP* for sending contact form responses to the configured Gmail account.

**Comment by codeit13** [comment]
I want to work on this issue.
And also where are we hosting this website.

**Comment by chiraag-kakar** [comment]
@codeit13 , can't assign the issue before 21st , till then check out the codebase and get the project running locally :)
Currently the website is being hosted in the pythonanywhere server.

[Click here to view the deployed app](https://wecreate.pythonanywhere.com)

**Comment by codeit13** [comment]
OK. Thanks

**Comment by amanjha8100** [comment]
I want to work on the issue.

**Comment by 7saikat7** [comment]
I can work on it , we can also try  email verification to eliminate the spam user ...how it will be sir ?

**Comment by chiraag-kakar** [comment]
@amanjha8100  , I am assigning this issue to you. Make sure you are able to solve it on time else the issue will be assigned to next participant.

**Comment by amanjha8100** [comment]
ok bhaiya

**Comment by chiraag-kakar** [comment]
@7saikat7 , If the issue is not solved by @amanjha8100 then you will be assigned this issue after a period of 3 days.
