### ISSUE TITLE
Add Footer Section

### ISSUE THREAD

**Issue by chiraag-kakar** [chiraag-kakar/sharenlearn#5]
The following elements need to be added in the Footer section : 
* The Background color class for the footer should be `dark`.
* The foreground color for the elements should be `white`.
* Include a small *iframe of Google Maps* in the right corner of the footer section.
* Social Media icons to be included: *Linkedin, Facebook, Twitter, Instagram*. (currently, they should be linked to `#`)
*  The copyright text should be included in the footer section.
* The Footer section should be extended to all templates.

**Comment by luckykumarirai** [comment]
I would like to contribute to this issue as a participant of jwoc.

**Comment by chiraag-kakar** [comment]
@luckykumarirai you can follow the readme to get a know-how of project setup. Issues can't be assigned before 21st Jan

**Comment by Pabitra145** [comment]
As a part of JWOC I would like to work on it

**Comment by chiraag-kakar** [comment]
@Pabitra145 I am assigning this issue to you

**Comment by Pabitra145** [comment]
Thank you sir

**Comment by chiraag-kakar** [comment]
@Pabitra145 , as you have not reverted , I am unassigning the issue to you

**Comment by harshita2216** [comment]
I would like to contribute to this issue. (JWoC Mentee)

**Comment by shreetama123** [comment]
hello, I want to work in this issue

**Comment by harshita2216** [comment]
#44
