### ISSUE TITLE
Chat Bot Development

### ISSUE THREAD

**Issue by codeit13** [chiraag-kakar/sharenlearn#55]
A FAQ chatbot for the website.

Following Chips will be made in the bot alongside the FAQ section
1) REQUEST MATERIAL --> For requesting additional Study Material in the Site.
2)REQUEST FEATURE --> For requesting additional features in the Site

**Comment by kunal299** [comment]
@codeit13 Hey, I would love to contribute to this issue as a part of Gssoc'21. Could you plz assign me?

**Comment by harshita2216** [comment]
Hi @chiraag-kakar. I'd like to contribute to this issue.

**Comment by amanjha8100** [comment]
@harshita2216 I am assigning this issue to you. It is a level three issue you have 5 days to solve this issue and submit the PR for the same.

**Comment by harshita2216** [comment]
@amanjha8100 I am now one of the mentors of Share N Learn.

**Comment by amanjha8100** [comment]
This issue is up for grab.

**Comment by tanishq-arya** [comment]
Hi @amanjha8100  I am interested in working on this issue under GSSOC. I am new to opensource as well I have not made a chatbot before. If you could point me in the right direction I can learn and work on this issue side by side.

**Comment by tanishq-arya** [comment]
Should I  follow rasa tutorial for chatbot or the python one ?

**Comment by tanishq-arya** [comment]
![Screenshot (961)_LI](https://user-images.githubusercontent.com/77333275/111587557-62855600-87e8-11eb-92cd-d741e946eaeb.jpg)
This is the dialogflow. I will now start creating the intents and responses on dialogflow from today.

**Comment by amanjha8100** [comment]
Yeah go ahead with dialogue flow. Remember the point that the chatbot just needs to solve some common issues that people might have while visiting the website. Keep it simple and effective.

**Comment by amanjha8100** [comment]
Going for choices was just a suggestion,if you can get the job done using just simple messages then also it's all right. In the first place it is important to design a chatbot first, the program is three months long we can always create further issues based on chatbot development.
