### ISSUE TITLE
Improve the User Sign Up / Sign In Page User Interface

### ISSUE THREAD

**Issue by chiraag-kakar** [chiraag-kakar/sharenlearn#6]
* Replace the existing basic user interface with a better and clean one.
* The Form should be responsive, clean, and minimally animated.

**Comment by pankajkumarbij** [comment]
I would like to work on this issue as a participant of JWOC.

**Comment by chiraag-kakar** [comment]
@pankajkumarbij follow the project setup docs and feel free to ping any queries in the project channel of JWOC. Issues can't be assigned before 21st Jan

**Comment by Malvika18** [comment]
can i contribute to this

**Comment by Pabitra145** [comment]
As a part of JWOC I would like to work on it

**Comment by chiraag-kakar** [comment]
@Malvika18 , Assigning this issue to you. Issues labelled easy need to solved in 1 day else it will assigned to the next participant.

**Comment by Malvika18** [comment]
@chiraag-kakar please review my PR
