### ISSUE TITLE
Feat : Improving contact form UI 

### ISSUE THREAD

**Issue by WaderManasi** [chiraag-kakar/sharenlearn#66]
### I would like to work on it, as part of gssoc'21

![contact](https://user-images.githubusercontent.com/52437677/110438611-9079e480-80dc-11eb-9fab-0755cfeeaf56.PNG)

**Comment by RaveenaBhasin** [comment]
Please assign it to me

**Comment by srisatya1197** [comment]
I want to contribute to this issue. Please assign me this task as a part of GSSoC'21

**Comment by Anshika-Srivastava** [comment]
I want to contribute to this issue. Please assign me this task as a part of GSSoC'21

**Comment by Koderz-SI** [comment]
I would like to contribute to this issue as a part of GSSOC'21!
Changes that would like to do:
1. Since the background has a cosmo effect.. we can use glass morphism.
2. The button can be given a gradient look as well.

**Comment by SanskritiKushik5** [comment]
I would like to contribute to this issue as a part of GSSOC'21!
Changes that would like to do:
1. Since the background has a cosmo effect.. we can use glass morphism.
2. The button can be given a gradient look as well.

**Comment by harshita2216** [comment]
@WaderManasi Make sure you only make changes to the UI.

**Comment by WaderManasi** [comment]
Sure @harshita2216
