### ISSUE TITLE
Account activation via email confirmation

### ISSUE THREAD

**Issue by jkrlr** [chiraag-kakar/sharenlearn#67]
When someone creating an account on Share N Learn website, a user can register via fake email id as shown in screenshot below. 
So, to avoid dummy creating dummy accounts. We should verify the user by sending the activation link on their email id.

As a participant of GSSoC'21. I would like to work on this issue.
@chiraag-kakar Please assign this issue to me.

![Screenshot from 2021-03-10 12-26-29](https://user-images.githubusercontent.com/63921263/110589961-27a67100-819d-11eb-93e2-13a3f96eaafd.png)

**Comment by amanjha8100** [comment]
@jkrlr I am assigning this issue to you.

**Comment by viraldevpb** [comment]
I am getting this error to set up this project on my local machine can anybody please help me.
![error](https://user-images.githubusercontent.com/66899360/111025153-6b50e300-8408-11eb-8d45-c9054d189951.png)

**Comment by jkrlr** [comment]
@amanjha8100 Can you please guide me how to resolve this error that I'm getting while installing requirements.txt file.

![Screenshot from 2021-03-14 15-38-14](https://user-images.githubusercontent.com/63921263/111064793-239b8b80-84dc-11eb-945b-5604d965965f.png)

**Comment by amanjha8100** [comment]
Guys, plzz contact me on discord, I will help you out.

**Comment by viraldevpb** [comment]
Send Me the link of the Discord.

**Comment by ashutoshkrris** [comment]
> I am getting this error to set up this project on my local machine can anybody please help me.
> ![error](https://user-images.githubusercontent.com/66899360/111025153-6b50e300-8408-11eb-8d45-c9054d189951.png)

because you are inside the myenv directory.
Just come one step back using `cd ..` and then run the command

**Comment by viraldevpb** [comment]
@ashutoshkrris  But we have to install requirements.txt on our environment as mentioned in the Readme.md File.

**Comment by ashutoshkrris** [comment]
Yes
But it doesn't mean , that you have to install the requirements in the myenv directory.
It means, first activate the enviroment using `. myenv/Scripts/activate` and then install the requirements

**Comment by coding-geek21** [comment]
@amanjha8100  Can i work on this issue?? If it is not updated??
