### ISSUE TITLE
Revamping the Navbar and user login form

### ISSUE THREAD

**Issue by shreya9301** [chiraag-kakar/sharenlearn#69]
![sharenlearn_issue1](https://user-images.githubusercontent.com/65105127/110746984-ab2a9580-8263-11eb-898f-a255edc37105.PNG)
### As a GSSoc'21 participant, I would like to revamp the navbar and user login form. Please allow me to work on this issue.

**Comment by harshita2216** [comment]
@shreya9301 For now, only work on the user login form.

**Comment by shreya9301** [comment]
Sure I'll work on that. Thank you @harshita2216 for assigning this issue to me :)

**Comment by subhangi2731** [comment]
please assign me this
