### ISSUE TITLE
Improve the User Interface for Admin Log In Page

### ISSUE THREAD

**Issue by chiraag-kakar** [chiraag-kakar/sharenlearn#7]
* Replace the existing basic user interface with a better and clean one.
* The Form should be responsive, clean, and minimally animated.

**Comment by luckykumarirai** [comment]
I would like to contribute to this issue.

**Comment by chiraag-kakar** [comment]
@luckykumarirai , follow the project setup docs and try to run it locally. It's great to see that you are interested to attempt the issue. But issues can't be assigned before 21st Jan.

**Comment by Malvika18** [comment]
can i work on this

**Comment by 435akashjha** [comment]
I want to work on this issue

**Comment by chiraag-kakar** [comment]
@435akashjha , I am assigning this issue to you.

**Comment by nikitajuneja1** [comment]
Hi, I would love to work on this issue. Please assign it to me.

**Comment by micksharma** [comment]
Can I work on this issue as a GSSOC 2021 participant.

**Comment by machine-sg** [comment]
I am a GSSOC'21 participant and I wish to work on this . Hope to hear back from you . 
There will be 3 parts of this page 
1) Header with navbar
2) Main body
3) Footer
Thank you .

**Comment by kalpanapurohit** [comment]
I would like to work on this issue as a GSSOC'21 participant.

**Comment by ayushgupta0110** [comment]
I would like to contribute to this issue. Kindly assign this to me as a part of GSSoc'21.

**Comment by GarimaKhare15** [comment]
I would like to work on this issue . Please assign this to me .
I'm a GSSOC'21 participant.

**Comment by amanjha8100** [comment]
@nikitajuneja1 assigned this issue to you.

**Comment by Dimple115** [comment]
Hey, I'm gssoc'21 participant, I would like to give my hand in this project. Please assign this issue to me. @amanjha8100
