### ISSUE TITLE
fix laggy about page

### ISSUE THREAD

**Issue by mohammedjameel24** [chiraag-kakar/sharenlearn#70]
fixing the stutter in the about page

**Comment by mohammedjameel24** [comment]
While setting up the project locally 
Got this error while installing requirements.txt

# No matching distribution found for pycryptodome==3.9.8_

**Comment by mohammedjameel24** [comment]
Am not able to set it up locally

**Comment by amanjha8100** [comment]
I have solved this problem, do check conversations in project channel.

**Comment by mohammedjameel24** [comment]
> I have solved this problem, do check conversations in project channel.
> 

Couldn't find Angy channel link

**Comment by amanjha8100** [comment]
U r in gssoc right?

**Comment by mohammedjameel24** [comment]
> U r in gssoc right?

Yes ok understood discord
