### ISSUE TITLE
Scroll back to top button and chatbot

### ISSUE THREAD

**Issue by Debashish-hub** [chiraag-kakar/sharenlearn#71]
Hello! I am a GSSOC'21 participant.

The scroll back to top button and a chatbot are the basic requirements for a website.
That would also help in customer engagement.

@chiraag-kakar I would like to work on this issue

**Comment by amanjha8100** [comment]
The Chat-Bot issue is already opened.

**Comment by Debashish-hub** [comment]
Can I work on scroll to top button only?
