### ISSUE TITLE
adding the website logo to the navbar, changing the color coding and the navbar style

### ISSUE THREAD

**Issue by oneknucklehead** [chiraag-kakar/sharenlearn#72]
the website logo is missing from the navbar and also the color-coding of the website is quite bland. The navbar should be shifted toward the right with the website logo to the left. The website needs an overall change.
Can I get assigned to this issue?

**Comment by harshita2216** [comment]
Hey, please check our discord server in a few days. We've been planning something for the project and for that we do not require this issue. Will announce as soon as we get the confirmation from the PA.
