### ISSUE TITLE
Add reCaptcha checkbox on login page

### ISSUE THREAD

**Issue by Equinox-13** [chiraag-kakar/sharenlearn#73]
@amanjha8100 I would like to add the Recaptcha checkbox on the login page as a GSSoC'21 participant.
Please assign this issue to me.
![image](https://user-images.githubusercontent.com/36486238/110932551-aba15a00-8351-11eb-8ee9-261e7c3bbc55.png)

Thank you.

**Comment by MayankBeck** [comment]
I would like to work on this issue under GSSoC 21. please assign this task to me. My discord id in GSSOC(GS)'s server is Mayank(P)#9695 .

**Comment by amanjha8100** [comment]
@Equinox-13 I am assigning this issue to you. If he is not able to complete it then Mayank you can try.

**Comment by 435akashjha** [comment]
@amanjha8100 Can I  work on this issue and solve it
