### ISSUE TITLE
signup is not working

### ISSUE THREAD

**Issue by flyingsonu122** [chiraag-kakar/sharenlearn#76]
after adding details then pressing sign up give this error ⬇️ 
![image](https://user-images.githubusercontent.com/51280276/111002914-3adb5b80-83ac-11eb-9bbd-c7c1180ee07c.png)

**Comment by amanjha8100** [comment]
@flyingsonu122  Assigned this issue to you.

**Comment by rk05-lenavo** [comment]
I'm the participant in GSSOC'21. Could you please assign me this.I would love working on this.

**Comment by flyingsonu122** [comment]
> I'm the participant in GSSOC'21. Could you please assign me this.I would love working on this.

It is already assigned to me

**Comment by flyingsonu122** [comment]
@amanjha8100 please **review** the PR #97
