### ISSUE TITLE
Changing the target link of the navbar item (after user login)"Home" and adding logo to the Navbar. 

### ISSUE THREAD

**Issue by ManuGupta9780** [chiraag-kakar/sharenlearn#77]
1. Currently, after we login to the website, the nav-bar item "HOME" directs us to the profile page of the user. Instead, it should direct the user to the initial home page of the "Share N Learn" website for better UI. User profile page can be reached through the profile option under the "welcome user" dropdown item.

2. Currently the NavBar doesn't contain the "sharenlearn" logo. Also, the Navbar items should be shited to the right for a better UI.

Before change:
![before pic](https://user-images.githubusercontent.com/59606099/111020024-05089800-83e9-11eb-9197-2b315302eca2.png)

After change:
![after pic1](https://user-images.githubusercontent.com/59606099/111020071-439e5280-83e9-11eb-901a-a1b4deed600c.png)

I would like to contribute to this issue as a participant of GSSOC'21.

**Comment by Dimple115** [comment]
Hey, I'm gssoc'21 participant, I would like to give my hand in this project. Please assign this issue to me.

**Comment by amanjha8100** [comment]
Will you create the logo yourself?

**Comment by ManuGupta9780** [comment]
@amanjha8100  I did not create the logo by myself. It was given in your readme file. It appeared that it might be the logo.

**Comment by harshita2216** [comment]
Hey both, please check our discord server in a few days. We've been planning something for the project and for that we do not require this issue. Will announce as soon as we get the confirmation from the PA.
