### ISSUE TITLE
Bug: Responsive Login Page

### ISSUE THREAD

**Issue by icoderharshit** [chiraag-kakar/sharenlearn#78]
Login page at present is not fully responsive. So, I want to make it responsive as a part of GSSoC'21. @chiraag-kakar Kindly assign me this issue so that I can do as mentioned.
#GSSoC'21.

**Comment by harshita2216** [comment]
@icoderharshit Can you show me the issue and explain how are you going to solve it?

**Comment by icoderharshit** [comment]
@harshita2216 It has been already done ig, and you are replying to me after 11 days of my comment :( So, maybe I'll have to look for more issues or bugs in the project. Kindly, assign them to me in time because I still haven't made any commit under GSSoC'21 yet.

**Comment by icoderharshit** [comment]
@harshita2216 I just got to see that Admin Login Page is not responsive, so may I fix it ? Assign me this issue.
PFA: screenshot of the issue found
![bugg](https://user-images.githubusercontent.com/55023091/112212252-c1acf580-8c42-11eb-9f76-0cef44222f79.JPG)

**Comment by harshita2216** [comment]
> @harshita2216 It has been already done ig, and you are replying to me after 11 days of my comment :( So, maybe I'll have to look for more issues or bugs in the project. Kindly, assign them to me in time because I still haven't made any commit under GSSoC'21 yet.

@icoderharshit Well, none of the PRs have been merged in 11 days, so nothing has changed since then :) 
About the admin page, it has already been assigned to someone. There are a lot of open issues, you can comment there and get yourself assigned.
