### ISSUE TITLE
Secure Django Admin

### ISSUE THREAD

**Issue by chiraag-kakar** [chiraag-kakar/sharenlearn#8]
* Secure the Django admin panel by making use of a package called *Admin-Honey-Pot*.

[*Django-Admin-Honeypot* is a fake Django admin login screen that will replace the admin login page with a fake admin login form.]

* This feature can be used to track the malicious attempts to access the Django admin.

**Comment by 7saikat7** [comment]
sir from JWOC , i want to work on it .....please assign me
