### ISSUE TITLE
Revamping the landing page to be more attractive

### ISSUE THREAD

**Issue by aashishah** [chiraag-kakar/sharenlearn#80]
The landing page of the website looks very dull and unattractive and I would like to redesign it as well as add an "about this app", "meet the team" etc. sections.

**Comment by aashishah** [comment]
I'd love to work on this issue under GSSOC'21, so it'd be great if you could assign it to me. Thank you!

**Comment by harshita2216** [comment]
Kindly explain how you would improve it? @aashishah

**Comment by harshita2216** [comment]
Closing this issue as I have not heard from you in a long time. @aashishah
