### ISSUE TITLE
Scroll back to top button

### ISSUE THREAD

**Issue by Debashish-hub** [chiraag-kakar/sharenlearn#82]
Hello everyone!

I am a GSSOC'21 participant. 
I want to work on scroll back to top button for the website.

@chiraag-kakar It will be great if I will get assigned on this issue. Thank you

**Comment by 435akashjha** [comment]
@harshita2216 Can you assign this issue to me for solving

**Comment by rk05-lenavo** [comment]
I am a GSSoC'21 participant @harshita2216 
Can you assign me this issue

**Comment by simranbhalla3** [comment]
I am a Gssoc participant , please assign me this issue.

**Comment by satwik-talluri** [comment]
Hello!

I am a GSSOC'21 participant.
I would love to work on scroll back to top button for the website.

@chiraag-kakar and @harshita2216  can you please assign me this issue if it's not already resolved. Thank you
