### ISSUE TITLE
Adding some images related to this website

### ISSUE THREAD

**Issue by fatma-sia27** [chiraag-kakar/sharenlearn#88]
Hey, I visited your website and I found that if  we will add some photos reated to books ansd all then it will look more creative and decent. So I can do that please assign this issue to me.
Thank you

**Comment by amanjha8100** [comment]
Fatima I am getting your point but the changes you are suggesting is quite subjective, you may like those photos but maybe the PA won't like it, these changes are minor and very subjective. I believe lets let the PA decide the photos. Feel free raise other issues. Thanking you for creating this one.
