### ISSUE TITLE
A blogpost page for share&learn 


### ISSUE THREAD

**Issue by mohammedjameel24** [chiraag-kakar/sharenlearn#89]
To make home page more interactive 
This will help us provide typed content and source pdfs or content notes

**Comment by amanjha8100** [comment]
We don't really need blogpost right now, but if you could give a proper explanation for how blogs will be helpful relating to this project, we can consider. Please give your explanation in project channel.

**Comment by harshita2216** [comment]
@mohammedjameel24 Closing this, for now, will reopen if needed.
