### ISSUE TITLE
Create Sitemap

### ISSUE THREAD

**Issue by chiraag-kakar** [chiraag-kakar/sharenlearn#9]
* Create an XML sitemap for the web application.
* Include a link to the sitemap somewhere in the footer section.
* Any suitable package that is compatible with the dependencies and Django version is accepted

**Comment by Abhra303** [comment]
want to work on this issue....

**Comment by Abhra303** [comment]
As a JWOC mentee

**Comment by 7saikat7** [comment]
sir i also want to work on that issue .... a default site map which django will create ,  i am also from JWOC ,It will be really helpful if  you assign me that

**Comment by chiraag-kakar** [comment]
@Abhra303 , Okay I am assigning this issue to you. You can ping your queries in the project channel and progress in the issue thread.
