### ISSUE TITLE
In sign up page :- Contact validation of 10 digit 

### ISSUE THREAD

**Issue by kumarishalini6** [chiraag-kakar/sharenlearn#91]
In sign up form there should be  validation of 10 digit number . I want to work on this issue as a participate of gssoc21 .

**Comment by amanjha8100** [comment]
Issue assigned.

**Comment by 435akashjha** [comment]
@amanjha8100 Can I work on this issue and solve it

**Comment by amanjha8100** [comment]
If shalini is not able to solve the isuue @435akashjha . I will assign to it you.

**Comment by kumarishalini6** [comment]
Sir I am working on it , the thing is I am busy in clg 
I will send you by today

**Comment by kumarishalini6** [comment]
Sorry @435akashjha but I am working on it

**Comment by kumarishalini6** [comment]
@amanjha8100 i have send PR please check it
