### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by jkrlr** [chiraag-kakar/sharenlearn#92]
As you mentioned on discord this project has been made in python3.7(After knowing this fact I have locally setup this project via python3.7 without updating the requirements.txt file). So, I want to update python downloading link to python version 3.7 and mention the steps to creating virtualenv by python3.7. So, that a new contributor wouldn't be required to update requirements.txt 

Also, I want to mention the command to activating the virtualenv (currently not there in readme) for linux as well and one more thing I want to update cloning the repo command( currently mentioned command in readme `git clone https://github.com/chiraag-kakar/sharenlearn.git`   updated should be `git clone https://github.com/<your-github-username>/sharenlearn.git` 

Since, In GSSOC peoples will be staying with this project for 3 months, Then one can contribute many times . So, that person should required to sync their local master with the main project master. Hence, For ease of other contributors for contributing, I want to add command for this also.

**Comment by viraldevpb** [comment]
@jkrlr can u send the discord link?

**Comment by jkrlr** [comment]
> @jkrlr can u send the discord link?

@viraldevpb I'm not a mentor or admin of this project. So , I haven't privileged to send discord link. You may asks for mentors or the project admin for regarding this. One thing is that If you are on official discord server of GSSOC'21 , you can can find there this as well as other GSSOC projects link.

**Comment by 435akashjha** [comment]
@harshita2216 Can you assign this issue to me
